version: '3.8'

services:
  application:
    image: ghcr.io/alexbidenko1998/asmy-docs:latest
    networks:
      - server
    deploy:
      replicas: 1
      update_config:
        failure_action: rollback
        order: start-first
      restart_policy:
        condition: on-failure

networks:
  server:
    external: true
